Repository betagouv/oots-france, pull requests merged in 2023-11, with the labels that each got.

#23 Utilise une instance Domibus lancée depuis un conteneur Docker
  .env.domibus.template
  .env.template
  .gitignore
  docker-compose.yml
Labels: enhancement

#25 Fixe vulnérabilités Semver détectées par `npm audit`
  package-lock.json
  package.json
Labels: dependencies

#24 Ajoute un fichier `README.md`
  README.md
  exemples/configuration_PMode_Domibus.xml
Labels: documentation

#26 N'affiche pas les logs Domibus
  docker-compose.yml
Labels: enhancement

#29 Pose un interrupteur sur l API /requete/diplomeSecondDegre
  .env.oots.template
  server.js
  src/adaptateurs/adaptateurEnvironnement.js
  src/ootsFrance.js
  test/ootsFrance.spec.js
Labels: enhancement
