Repository betagouv/oots-france, pull requests merged in 2024-03, with the labels that each got.

#68 Supprime informations en session sur erreur récupération infos utilisateur depuis FC+
  src/api/connexionFCPlus.js
  test/api/connexionFCPlus.spec.js
Labels: bug, pending

#72 [CORRECTION] Forme correctement URL action SOAP
  src/adaptateurs/adaptateurDomibus.js
Labels: bug, urgent

#73 Corrige le champs EvidenceTypeClassification
  src/ebms/requeteJustificatif.js
Labels: bug

#74 Injecte un identifiant eIDAS dans requête Domibus
  .env.oots.template
  src/api/pieceJustificative.js
  src/ebms/requeteJustificatif.js
  test/api/pieceJustificative.spec.js
  test/ebms/requeteJustificatif.spec.js
  test/ebms/utils.js
Labels: enhancement, urgent

#76 [CORRECTION] utilise valeurs correctes pour propriétés `originalSender` et `finalRecipient`
  src/ebms/entete.js
  test/ebms/enteteRequete.spec.js
Labels: bug
