Repository betagouv/oots-france, pull requests merged in 2024-04, with the labels that each got.

#77 [NETTOYAGE] Utilise `AdaptateurEnvironnement`
  src/adaptateurs/adaptateurEnvironnement.js
  src/api/pieceJustificative.js
  src/routes/routesRequete.js
  test/api/pieceJustificative.spec.js
  test/routes/serveurTest.js
Labels: code

#80 Ajoute route `GET /auth/fcplus/deconnexion`
  src/api/deconnexionFCPlus.js
  src/routes/routesAuth.js
  test/api/deconnexionFCPlus.spec.js
  test/routes/routesAuth.spec.js
Labels: enhancement

#83 Inverse dépendance entre `SessionFCPlus` et `adaptateurFranceConnectPlus`
  src/adaptateurs/adaptateurFranceConnectPlus.js
  src/api/connexionFCPlus.js
  src/modeles/sessionFCPlus.js
  test/api/connexionFCPlus.spec.js
  test/modeles/sessionFCPlus.spec.js
  test/routes/routesAuth.spec.js
  test/routes/serveurTest.js
Labels: code

#84 Destruction de la session FC+ depuis un lien « Se déconnecter » sur la page d'accueil
  .env.oots.template
  src/adaptateurs/adaptateurEnvironnement.js
  src/adaptateurs/adaptateurFranceConnectPlus.js
  src/api/destructionSessionFCPlus.js
  src/ootsFrance.js
  src/routes/routesAuth.js
  src/routes/routesBase.js
  test/api/destructionSessionFCPlus.spec.js
  test/routes/routesAuth.spec.js
  test/routes/serveurTest.js
Labels: enhancement

#87 Vérifie présence JWT session avant destruction session FC+
  src/api/destructionSessionFCPlus.js
  test/api/destructionSessionFCPlus.spec.js
Labels: enhancement

#88 [CORRECTION] Mise à jour du comportement du serveur mock FC+
  .env.template
  docker-compose.yml
  mockFCPlus.js
Labels: bug

#89 Utilise un moteur de template Mustache
  package-lock.json
  package.json
  src/ootsFrance.js
  src/routes/routesBase.js
  src/vues/pageAccueil.mustache
Labels: code
