Repository betagouv/oots-france, pull requests merged in 2024-02, with the labels that each got.

#49 Utilise clé privée pour exposer clé publique sous forme d'un JWK Set
  .env.oots.template
  server.js
  src/adaptateurs/adaptateurChiffrement.js
  src/adaptateurs/adaptateurEnvironnement.js
  src/ootsFrance.js
  test/ootsFrance.spec.js
Labels: code

#57 Vérifie qu'il ne reste pas de `it.only` dans les tests
  .eslintrc.js
  package-lock.json
  package.json
Labels: code

#52 Vérifie la signature du JWT reçu
  mockFCPlus.js
  src/adaptateurs/adaptateurFranceConnectPlus.js
  src/erreurs.js
  src/ootsFrance.js
  test/ootsFrance.spec.js
Labels: enhancement, pending

#64 Corrige l'attribut `Secure` sur le cookie de session
  src/ootsFrance.js
  test/routes/routesAuth.spec.js
  test/routes/serveurTest.js
Labels: bug

#65 Configure le trust-proxy du serveur Express
  src/ootsFrance.js
Labels: bug
